# Generated by Django 5.0 on 2024-01-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Electronics'), ('1', 'Fashion'), ('2', 'Health'), ('3', 'Hobby'), ('4', 'Sports'), ('5', 'Pets')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
    ]
